export  const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export  const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export  const ALL_PRODUCT_FAILURE = "ALL_PRODUCT_FAILURE"
export  const CLEAR = "CLEAR"

export  const DETAIL_PRODUCT_REQUEST = "DETAIL_PRODUCT_REQUEST"
export  const DETAIL_PRODUCT_SUCCESS = "DETAIL_PRODUCT_SUCCESS"
export  const DETAIL_PRODUCT_FAILURE = "DETAIL_PRODUCT_FAILURE"

